const summaryArray = [["Rwandan Revolution, Beginning of Congo Crisis, Beginning of Escalation of Vietnam War by US, First Sudanese Civil War, Tibetan Uprising, Great Leap Forward, Katanga insurgency in Congo"], //1960
					["Beginning of Angolan War of Independence, Rwandan Revolution, Beginning of First Iraqi-Kurdish War, Beginning of Eritrean War of Independence"],
					["End of Rwandan Revolution, End of Great Leap Forward, Beginning of North Yemen Civil War"],
					["Beginning of Guinea-Bissau War of Independence, Beginning of Mozambique War of Independence, End of Tibetan Uprising"],
					[""],
					["End of Congo Crisis, Greek Apostasia of 1965, Dominican Civil War, Beginning of American occupation of the Dominican Republic, Indo-Pakistani War of 1965, Beginning of Communist Insurgency in Thailand, Beginning of Chadian Civil War"],
					["End of American occupation of the Dominican Republic, Beginning of Korean DMZ Conflict, Beginning of South African Border War"],
					["Six-Day War, Kurdish revolt in Iran, Beginning of Araguaia Guerrilla War, Beginning of Cambodian Civil War, Beginning of Nigerian Civil War, Beginning of War of Attrition, Beginning of Naxalite-Maoist Insurgency"],
					["Beginning of Communist Insurgency in Malaysia, Beginning of Years of Lead, Warsaw Pact Invasion of Czechoslovakia"],
					["End of Korean DMZ Conflict, Beginning of Civil conflict in the Philippines, Sino-Soviet Border Conflict, Beginning of Papau Conflict"], 
					["End of Iraqi-Kurdish War, End of North Yemen Civil War, End of Nigerian Civil War, End of War of Attrition, Beginning of Black September in Jordan, Beginning of Dirty War (Mexico)"], //1970
					["End of Black September in Jordan, Bangladesh Liberation War, Indo-Pakistani War of 1971"],
					["End of First Sudanese Civil War, Beginning of First Eritrean Civil War, Beginning of Bangladesh Insurgency"],
					["End of Araguaia Guerrilla War, Yom Kippur War, Beginning of armed resistance in Chile, Oromo Conflict"],
					["End of Guinea-Bissau War of Independence, Beginning of Ethiopian Civil War, End of First Eritrean Civil War, Beginning of Second Iraqi-Kurdish War"],
					["End of Angolan War of Independence, End of Vietnam War, End of Mozambique War of Independence, End of Cambodian Civil War, End of Bangladesh Insurgency, End of Second Iraqi-Kurdish War, Beginning of Angolan Civil War, Beginning of Cabinda War, Beginning of Western Sahara War, Beginning of PUK Insurgency, Beginning of Lebanese Civil War, Beginning of Cambodian-Vietnamese War, Beginning of Insurgency in Laos"],
					["Beginning of Dirty War (Argentina), Beginning of political violence in Turkey"],
					["Beginning of Mozambican Civil War, Libyan-Egyptian War, Beginning of Ethio-Somali War, Shaba I"],
					["End of Ethio-Somali War, Shaba II, 1978 South Lebanon Conflict, Beginning of Uganda-Tanzania War, Beginning of Chadian-Libyan Conflict, Beginning of Turkey-PKK Conflict"],
					["End of Chadian Civil War, End of PUK Insurgency, End of Uganda-Tanzania War, 1979 Herat uprising, Yemenite War of 1979, 1979 Khuzestan uprising, Sino-Vietnamese War, Beginning of Islamist uprising in Syria, Beginning of 1979 Kurdish rebellion in Iran, Beginning of Al-Ansar Insurgency, Beginning of Soviet-Afghan War, Beginning of Salvadorian Civil War"],
					["End of political violence in Turkey, Coconut War, Beginning of internal conflict in Peru, Beginning of Iran-Iraq War, Beginning of Second Eritrean Civil War, Beginning of Maoist Insurgency in Turkey"], //1980
					["End of Second Eritrean Civil War, Paquisha War, 1981 Entumbane uprising, Beginning of Ugandan Bush War"],
					["End of Years of Lead, End of Dirty War (Mexico), End of Islamist uprising in Syria, Beginning of Casamance conflict, Falklands War, Beginning of 1982 Lebanon War Seucirty Zone Conflict, 1982 Ethiopian-Somali Border War"],
					["Beginning of Second Sudanese Civil War, Beginning of famine in Ethiopia, End of Communist Insurgency in Thailand, End of Dirty War (Argentina), End of 1979 Kurdish rebellion in Iran, Invasion of Grenada, Beginning of Sri Lankan Civil War, Beginning of Kurdish rebellion of 1983"],
					["Beginning of Siachen Conflict, Agacher Strip War, South Yemen Civil War, Beginning of Surinamese Interior War"],
					["End of famine in Ethiopia, End of Kurdish rebellion"],
					["End of Ugandan Bush War"],
					["End of Chadian-Libyan Conflict, End of Siachen Conflict, Beginning of Singing Revolution, Beginning of Thai-Laotian Border War, JVP Insurrection, Beginning of Lord's resistance Army Insurgency"],
					["End of Al-Ansar Insurgency, End of Iran-Iraq War, End of Thai-Laotian Border War, Bougainville Civil War, Beginning of Nagomo-Karabakh War"],
					["End of South African Border War, End of Communist Insurgency in Malaysia, End of Cambodian-Vietnamese War, End of Soviet-Afghan War, Beginning of Mauritania-Senegal Border War, US Invasion of Panama, Romanian Revolution, Beginning of First Liberian Civil War, KDPI Insurgency, Insurgency in Jammu and Kashmir"],
					["Beginning of Rwandan Civil War, End of armed resistance in Chile, End of Lebanese Civil War, Beginning of Gulf War, Beginning of DHKP/C insurgency in Turkey, Beginning of Tuareg rebellion, 1990 Mindanao crisis (Philippines)"], //1990
					["End of Ethiopian Civil War, End of Eritrean War of Independence, End of Western Sahara War, End of Singing Revolution, End of Mauritania-Senegal Border War, End of Gulf War, Ten-Day War, Beginning of South Ossetia War, Beginning of Djiboutian Civil War, Beginning of Croatian War of Independence, Beginning of Sierra Leone Civil War, Beginning of Algerian Civil War, Beginning of Somali Civil War, Beginning of Georgian Civil War, 1991 uprisings in Iraq"],
					["End of Mozambican Civil War, End of Salvadorian Civil War, End of Surinamese Interior War, End of South Ossetia War, Venezuelan coup d'etat attempts, East Prigorodny Conflict, Beginning of civil war in Afghanistan, War of Transnistria, Beginning of War in Abkhazia, Beginning of Bosnian War, Beginning of civil war in Tajikistan"],
					["End of Rwandan Civil War, End of Georgian Civil War, End of War in Abkhazia, Beginning of Burundian Civil War, Beginning of ethnic conflict in Nagaland, 1993 Russian constitutional crisis"],
					["End of Nagomo-Karabakh War, End of Djiboutian Civil War, Beginning of Iraqi Kurdish Civil War, Beginning of Armenian-Azerbaijani border conflict, 1994 Zapatista Uprising, 1994 civil war in Yemen, Bophusthatswana conflict, Beginning of First Chechen War, Beginning of Caprivi conflict"],
					["End of Tuareg rebellion, End of Croatian War of Independence, End of Bosnian War, Cenepa War, Beginning of insurgency in Ogaden, Beginning of Second Afar Insurgency, Hanish Islands conflict"],
					["Beginning of First Congo War, End of First Liberian Civil War, End of KDPI Insurgency, End of civil war in Afghanistan, End of First Chechen War, Beginning of ADF Insurgency, Beginning of Nepalese Civil War, Beginning of second civil war in Afghanistan, Beginning of First Congo War"],
					["End of First Congo War, End of civil war in Tajikistan, End of Iraqi Kurdish Civil War, End of First Congo War, Albanian Rebellion of 1997, Beginning of Republic of the Congo Civil War, 1997 clashes in Cambodia, War in Abkhazia, Beginning of Kosovo War, Beginning of Eritrean-Ethiopian War, Beginning of Second Congo War"],
					["Beginning of Second Congo War, Beginning of Eritrean-Ethiopian War, End of Republic of the Congo Civil War, End of Kosovo War, Beginning of Guinea-Bissau Civil War, Beginning of Al-Qaeda insurgency in Yemen"],
					["End of Caprivi conflict, End of Guinea-Bissau Civil War, Kargil War, East Timorese crisis, Beginning of insurgency in the Presevo Valley, Beginning of Maluku sectarian conflict, Beginning of Second Liberian Civil War, Beginning of Ituri conflict, War of Dagestan, Beginning of Second Chechen War"],
					["End of Eritrean-Ethiopian War, End of Lebanon War Security Zone Conflict, End of Eritrean-Ethiopian War, Beginning of Second Intifada"], //2000
					["End of civil war in Afghanistan, End of insurgency in the Presevo Valley, Insurgency in the Republic of Macedonia, Beginning of War on Terror"],
					["End of Angolan Civil War, End of Sierra Leone Civil War, End of Algerian Civil War, End of Maluku Sectarian Conflict, Beginning of Operation Enduring Freedom - Philippines and Horn of Africa, Beginning of First Ivorian Civil War, Beginning of Taliban insurgency"],
					["End of Second Congo War, End of Second Liberian Civil War, Beginning of War in Darfur, Beginning of Iraq War, Beginning of Balochistan conflict"],
					["Beginning of War in North-West Pakistan, Kondovo Crisis, Beginning of Central African Republic Bush War, Beginning of Iran-PJAK conflict, Beginning of conflict in the Niger Delta, Beginning of Houthi Insurgency in Yemen, Beginning of Kivu conflict, Beginning of Sistan and Baluchestan Insurgency"],
					["End of Second Sudanese Civil War, End of Burundian Civil War, End of Second Intifada, Beginning of Paraguayan People's Army Insurgency, Beginning of Chadian Civil War, Beginning of Mount Elgon insurgency"],
					["End of Nepalese Civil War, End of Central African Republic Bush War, Beginning of Fatah-Hamas conflict, 2006 Lebanon War, Beginning of Mexican Drug War"],
					["End of Ituri Conflict, End of First Ivorian Civil War, Beginning of Operation Enduring Freedom - Trans Sahara, Beginning of War in Ingushetia"],
					["End of Mount Elgon insurgency, 2008 invasion of Anjouan, 2008 Kufra conflict, Beginning of Cambodian-Thai border dispute, Djiboutian-Eritrean border conflict, Russo-Georgian War, Beginning of Gaza War,"],
					["End of Sri Lankan Civil War, End of Second Chechen War, Beginning of Sudanese nomadic conflicts, Beginning of Insurgency in the North Caucasus, Beginning of Boko Haram Insurgency, Peruvian political crisis, Beginning of South Yemen Insurgency, Dongo confict"],
					["End of Chadian Civil War, South Kyrgyzstan ethnic clashes, Kingsston unrest, Beginning of Tajikistan Insurgency, Ivorian crisis"], //2010
					["End of Iraq War, End of Fatah-Hamas conflict, Libyan Civil War, Beginning of Sinai Insurgency, Beginning of Syrian Civil War, Beginning of Sudanese conflict in South Kordofan and Blue Nile, Beginning of Shia insurgency in Bahrain, Beginning of Syrian Civil War spillover in Lebanon, Ethnic violence in South Sudan, Beginning of factional violence in Libya"],
					["End of Cambodian-Thai border dispute, End of Tajikistan Insurgency, Northern Mali conflict, Heglig Crisis, M23 rebellion, Baragoi clashes, Beginning of Central African Republic conflict"],
					["Beginning of South Sudanese Civil War, Beginning of Batwa-Luba clashes, Beginning of RENAMO insurgency"],
					["Beginning of Iraqi Civil War, Beginning of Libyan Civil War, Beginning of War in Donbass, Beginning of military intervention against ISIL"],
					["End of Houthi Insurgency in Yemen, End of War in Ingushetia, Beginning of Yemeni Civil War, Beginning of ISIL Insurgency in Tunisia, Beginning of Kurdish-Turkish conflict"],
					["Beginning of 2016 Niger Delta conflict, Armenian-Azerbaijani clashes, The Pool War, Beginning of Northern Rakhine State clashes, Kasese clashes, Beginning of Kamwina Nsapu rebellion"],
					["2017 Afghanistan-Pakistan border skirmish, Iraqi-Kurdish conflict, Qatif unrest, Beginning of Anglophone crisis, Beginning of Islamist insurgency in Mozambique, Beginning of Iraqi insurgency"] //2017	
]