const summaryArray = [["Rwandan Revolution, Beginning of Congo Crisis, Beginning of Escalation of Vietnam War by US, First Sudanese Civil War, Tibetan Uprising, Great Leap Forward, Katanga insurgency in Congo"], //1960
					["Beginning of Angolan War of Independence, Rwandan Revolution, Beginning of First Iraqi-Kurdish War, Beginning of Eritrean War of Independence"],
					["End of Rwandan Revolution, End of Great Leap Forward, Beginning of North Yemen Civil War"],
					["Beginning of Guinea-Bissau War of Independence, Beginning of Mozambique War of Independence, End of Tibetan Uprising"],
					[""],
					["End of Congo Crisis, Greek Apostasia of 1965"],
					[""],
					[""],
					[""],
					[""], 
					["End of Iraqi-Kurdish War, End of North Yemen Civil War"], //1970
					[""],
					["End of First Sudanese Civil War"],
					[""],
					["End of Guinea-Bissau War of Independence, Beginning of Ethiopian Civil War"],
					["End of Angolan War of Independence, End of Vietnam War, End of Mozambique War of Independence"],
					[""],
					[""],
					[""],
					[""],
					[""], //1980
					[""],
					[""],
					["Beginning of Second Sudanese Civil War, Beginning of famine in Ethiopia"],
					[""],
					["End of famine in Ethiopia"],
					[""],
					[""],
					[""],
					[""],
					["Beginning of Rwandan Civil War"], //1990
					["End of Ethiopian Civil War, End of Eritrean War of Independence"],
					[""],
					["End of Rwandan Civil War"],
					[""],
					[""],
					["Beginning of First Congo War"],
					["End of First Congo War"],
					["Beginning of Second Congo War, Beginning of Eritrean-Ethiopian War"],
					[""],
					["End of Eritrean-Ethiopian War"], //2000
					[""],
					[""],
					["End of Second Congo War"],
					[""],
					["End of Second Sudanese Civil War"],
					[""],
					[""],
					[""],
					[""],
					[""], //2010
					[""],
					[""],
					[""],
					[""],
					[""],
					[""],
					[""] //2017	
]